# Change these first
owner: sakhalinfox # Your GitHub organization or username, where this repository lives
repo: orangepilldevuptime # The name of this repository

sites:
  - name: Nostr relay websocket connectivity check - wss://nostr.orangepill.dev
    check: "ws"
    url: wss://nostr.orangepill.dev
  - name: Nost Public Relay Response time - wss://nostr.orangepill.dev
    url: https://nostr.orangepill.dev
  - name: Nostr Relay - wss://relay.valera.co
    check: "ws"
    url: wss://relay.valera.co
  - name: Nostr Relay - wss://nostrical.com
    url: https://nostrical.com
  - name: Nostr Relay - wss://no.str.cr
    url: https://no.str.cr
  - name: Nostr Relay - wss://paid.no.str.cr
    url: https://paid.no.str.cr
  - name: Nostr Relay - wss://nostr.fly.dev
    url: https://nostr.fly.dev
  - name: Nostr Relay - wss://public.nostr.swissrouting.com
    url: https://public.nostr.swissrouting.com
  - name: Nostr Relay - wss://nostr.swiss-enigma.ch
    url: https://nostr.swiss-enigma.ch
  - name: Nostr Relay - wss://nostr.chaker.net
    url: https://nostr.chaker.net
  - name: Nostr Relay - wss://nostr.thesimplekid.com
    url: https://nostr.thesimplekid.com
  - name: Nostr Relay - wss://knostr.neutrine.com
    url: https://knostr.neutrine.com
  - name: Nostr Relay - wss://relay.damus.io
    url: https://relay.damus.io
  - name: Nostr Relay - wss://nostr-relay.wlvs.space
    url: https://nostr-relay.wlvs.space
  - name: Nostr Relay - wss://nostr-pub.wellorder.net
    url: https://nostr-pub.wellorder.net
  - name: Nostr Relay - wss://nostr.bitcoiner.social
    url: https://nostr.bitcoiner.social
  - name: Nostr Relay - wss://nostr.onsats.org
    url: https://nostr.onsats.org
  - name: Nostr Relay - wss://nostr.zebedee.cloud
    url: https://nostr.zebedee.cloud
  - name: Nostr Relay - wss://relay.nostr.info
    url: https://relay.nostr.info
  - name: Nostr Relay - wss://nostr-pub.semisol.dev
    url: https://nostr-pub.semisol.dev
  - name: Nostr Relay - wss://nostr.oxtr.dev
    url: https://nostr.oxtr.dev
  - name: Nostr Relay - wss://nostr.fmt.wiz.biz
    url: https://nostr.fmt.wiz.biz
  - name: Nostr Relay - wss://nostr.walletofsatoshi.com
    url: https://nostr.walletofsatoshi.com
  - name: Nostr Relay - wss://brb.io
    url: https://brb.io
  - name: Nostr Relay - wss://nostr-relay.untethr.me
    url: https://nostr-relay.untethr.me
  - name: Nostr Relay - wss://relay.nostr.scot
    url: https://relay.nostr.scot
  - name: Nostr Relay - wss://relay.nostr.bingo
    url: https://relay.nostr.bingo
  - name: Nostr Relay - wss://lightningrelay.com
    url: https://lightningrelay.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.orangepill.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Sakhalinfox/orangepilldevuptime/master/assets/logo.png
  name: Orangepill.dev Uptime Status
  theme: dark
  #introTitle: "**Upptime**"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Home
      href: https://orangepill.dev
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  links:
    - rel: stylesheet
      href: https://raw.githubusercontent.com/Sakhalinfox/orangepilldevuptime/master/assets/css/custom.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
